name: advanced_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.5'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: 3.0.0
  test: ^1.16.0
dependencies:
  http: ^1.1.2
